scripts: rewrite and improve coding style
Signed-off-by: Shashank Baghel <theradcolor@gmail.com>

diff --git a/personal/kernel b/personal/kernel
--- a/personal/kernel
+++ b/personal/kernel
@@ -21,18 +21,18 @@ clear
 function checkout_source()
 {
     # Checkout build dir.
-    cd ${BUILD}
+    cd "${BUILD}" || exit
 }
 
 function type()
 {
     # Export build type
     BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-    if [ ${BRANCH} == "kernel-hmp" ]; then
+    if [ "${BRANCH}" == "kernel-hmp" ]; then
        export TYPE=hmp
-    elif [ ${BRANCH} == "kernel-eas" ]; then
+    elif [ "${BRANCH}" == "kernel-eas" ]; then
        export TYPE=eas
-    elif [ ${BRANCH} == "staging" ]; then
+    elif [ "${BRANCH}" == "staging" ]; then
        export TYPE=staging
     fi
 }
@@ -68,51 +68,51 @@ function build_clang()
 {
     checkout_source
     set_param
-    make O=$out clean
-    make O=$out mrproper
-    rm -rf $out/arch/arm64/boot
-    make O=$out ${CONFIG}
+    make O="${out}" clean
+    make O="${out}" mrproper
+    rm -rf "${out}"/arch/arm64/boot
+    make O="${out}" "${CONFIG}"
 
-    make O=$out CC="${CC}" \
+    make O="${out}" CC="${CC}" \
     CROSS_COMPILE="${GCC64}" \
     CROSS_COMPILE_ARM32="${GCC32}" \
     CLANG_TRIPLE="${CLANG_TRIPLE}" \
-    -j6  2>&1| tee $out/kernel.log
+    -j6  2>&1| tee "$out"/kernel.log
     
-    if [ -f $IMG ]; then
+    if [ -f "${IMG}" ]; then
         BUILD_END=$(date +"%s")
-        DIFF=$(${BUILD_END} - ${BUILD_START})
-        echo -e ${green}"Build completed in $(DIFF / 60) minute(s) and $(DIFF % 60) seconds."${green}
+        DIFF=$("${BUILD_END}" - "${BUILD_START}")
+        echo -e "${green}" "Build completed in $($DIFF / 60) minute(s) and $($DIFF % 60) seconds." "${green}"
         flash_zip
     else
-		echo -e ${red}"Build failed, please fix the errors first bish!"${red}
+		echo -e "${red}" "Build failed, please fix the errors first bish!" "${red}"
 	fi
 }
 
 function flash_zip()
 {
-    echo -e ${green}"Now making a flashable zip of kernel with AnyKernel3"${white}
+    echo -e "${green}" "Now making a flashable zip of kernel with AnyKernel3" "${white}"
 
     type
     check_camera
-    cd ${ANYKERNEL_DIR}
-    export ZIPNAME=rad-${TYPE}-${CAM_TYPE}-whyred.zip
+    cd "${ANYKERNEL_DIR}" || exit
+    export ZIPNAME=rad-"${TYPE}"-"${CAM_TYPE}"-whyred.zip
 
     # Cleanup and copy Image.gz-dtb to dir.
-    rm -f *.zip
+    rm -f ./*.zip
     rm -f Image.gz-dtb
-    cp $out/arch/arm64/boot/Image.gz-dtb ${ANYKERNEL_DIR}/
+    cp "$out"/arch/arm64/boot/Image.gz-dtb "${ANYKERNEL_DIR}"/
 
     # Build a flashable zip
-    zip -r9 ${ZIPNAME} * -x README.md .git
+    zip -r9 "${ZIPNAME}" ./* -x README.md .git
 }
 
 function check_camera()
 {
-    CAMERA="$(grep 'BLOBS' $BUILD/arch/arm64/configs/${CONFIG})"
-    if [ ${CAMERA} == "CONFIG_XIAOMI_NEW_CAMERA_BLOBS=y" ]; then
+    CAMERA="$(grep 'BLOBS' $BUILD/arch/arm64/configs/"${CONFIG}")"
+    if [ "${CAMERA}" == "CONFIG_XIAOMI_NEW_CAMERA_BLOBS=y" ]; then
             CAM_TYPE="newcam"
-        elif [ ${CAMERA} == "CONFIG_XIAOMI_NEW_CAMERA_BLOBS=n" ]; then
+        elif [ "${CAMERA}" == "CONFIG_XIAOMI_NEW_CAMERA_BLOBS=n" ]; then
             CAM_TYPE="oldcam"
     fi
 }
@@ -122,7 +122,7 @@ function check_camera()
 # Checkout to HMP branch
 checkout_source
 type
-if [ ${TYPE} != "hmp" ]; then
+if [ "${TYPE}" != "hmp" ]; then
        git checkout kernel-hmp
 fi
 clear
@@ -131,14 +131,14 @@ clear
 CONFIG=whyred_defconfig # Configuration for oldcam
 type
 check_camera
-echo -e ${green}"Building $TYPE for $CAM_TYPE with Clang"${white}
+echo -e "${green}" "Building $TYPE for $CAM_TYPE with Clang" "${white}"
 build_clang # build_clang or build_gcc
 
 # HMP newcam
 CONFIG=whyred-newcam_defconfig # Configuration for newcam
 type
 check_camera
-echo -e ${green}"Building $TYPE for $CAM_TYPE with Clang"${white}
+echo -e "${green}" "Building $TYPE for $CAM_TYPE with Clang" "${white}"
 build_clang # build_clang or build_gcc
 
 # Checkout to EAS branch
@@ -150,12 +150,12 @@ clear
 CONFIG=whyred_defconfig # Configuration for oldcam
 type
 check_camera
-echo -e ${green}"Building ${TYPE} for ${CAM_TYPE} with Clang"${white}
+echo -e "${green}" "Building $TYPE for $CAM_TYPE with Clang" "${white}"
 build_clang # build_clang or build_gcc
 
 # EAS newcam
 CONFIG=whyred-newcam_defconfig # Configuration for newcam
 type
 check_camera
-echo -e ${green}"Building $TYPE for ${CAM_TYPE} with Clang"${white}
+echo -e "${green}" "Building $TYPE for $CAM_TYPE with Clang" "${white}"
 build_clang # build_clang or build_gcc
diff --git a/personal/testbuild b/personal/testbuild
--- a/personal/testbuild
+++ b/personal/testbuild
@@ -2,12 +2,11 @@
 
 # Copyright (C) 2020 Shashank Baghel
 # Personal kernel build script for https://github.com/theradcolor/android_kernel_xiaomi_whyred
-# That will build four varient of kernel i.e 2-2(oldcam & newcam) varient of EAS and HMP
 
 # Set enviroment and vaiables
 out="/home/theradcolor/whyred/out/"
 BUILD="/home/theradcolor/whyred/kernel/"
-ANYKERNEL_DIR="/home/theradcolor/whyred/anykernel-test/"
+ANYKERNEL_DIR="/home/theradcolor/whyred/anykernel/"
 IMG="/home/theradcolor/whyred/out/arch/arm64/boot/Image.gz-dtb"
 BUILD_START=$(date +"%s")
 
@@ -24,18 +23,18 @@ clear
 function checkout_source()
 {
     # Checkout build dir.
-    cd ${BUILD}
+    cd "${BUILD}" || exit
 }
 
 function type()
 {
     # Export build type
     BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-    if [ ${BRANCH} == "kernel-hmp" ]; then
+    if [ "${BRANCH}" == "kernel-hmp" ]; then
        export TYPE=hmp
-    elif [ ${BRANCH} == "kernel-eas" ]; then
+    elif [ "${BRANCH}" == "kernel-eas" ]; then
        export TYPE=eas
-    elif [ ${BRANCH} == "staging" ]; then
+    elif [ "${BRANCH}" == "staging" ]; then
        export TYPE=staging
     fi
 }
@@ -71,60 +70,61 @@ function build_clang()
 {
     checkout_source
     set_param
-    make O=$out clean
-    make O=$out mrproper
-    rm -rf $out/arch/arm64/boot
-    make O=$out ${CONFIG}
+    make O="${out}" clean
+    make O="${out}" mrproper
+    rm -rf "${out}"/arch/arm64/boot
+    make O="${out}" "${CONFIG}"
 
-    make O=$out CC="${CC}" \
+    make O="${out}" CC="${CC}" \
     CROSS_COMPILE="${GCC64}" \
     CROSS_COMPILE_ARM32="${GCC32}" \
     CLANG_TRIPLE="${CLANG_TRIPLE}" \
-    -j6  2>&1| tee $out/kernel.log
+    -j6  2>&1| tee "$out"/kernel.log
     
-    if [ -f $IMG ]; then
+    if [ -f "${IMG}" ]; then
         BUILD_END=$(date +"%s")
-        DIFF=$(${BUILD_END} - ${BUILD_START})
-        echo -e ${green}"Build completed in $(DIFF / 60) minute(s) and $(DIFF % 60) seconds."${green}
+        DIFF=$("${BUILD_END}" - "${BUILD_START}")
+        echo -e "${green}" "Build completed in $($DIFF / 60) minute(s) and $($DIFF % 60) seconds." "${green}"
         flash_zip
     else
-		echo -e ${red}"Build failed, please fix the errors first bish!"${red}
+		echo -e "${red}" "Build failed, please fix the errors first bish!" "${red}"
 	fi
 }
 
 function flash_zip()
 {
-    echo -e ${green}"Now making a flashable zip of kernel with AnyKernel3"${white}
+    echo -e "${green}" "Now making a flashable zip of kernel with AnyKernel3" "${white}"
 
     type
     check_camera
-    cd ${ANYKERNEL_DIR}
-    export ZIPNAME=rad-${TYPE}-${CAM_TYPE}-whyred.zip
+    cd "${ANYKERNEL_DIR}" || exit
+    export ZIPNAME=rad-"${TYPE}"-"${CAM_TYPE}"-whyred.zip
 
     # Cleanup and copy Image.gz-dtb to dir.
-    rm -f *.zip
+    rm -f ./*.zip
     rm -f Image.gz-dtb
-    cp $out/arch/arm64/boot/Image.gz-dtb ${ANYKERNEL_DIR}/
+    cp "$out"/arch/arm64/boot/Image.gz-dtb "${ANYKERNEL_DIR}"/
 
     # Build a flashable zip
-    zip -r9 ${ZIPNAME} * -x README.md .git
+    zip -r9 "${ZIPNAME}" ./* -x README.md .git
     tg_push
 }
 
 function check_camera()
 {
-    CAMERA="$(grep 'BLOBS' $BUILD/arch/arm64/configs/${CONFIG})"
-    if [ ${CAMERA} == "CONFIG_XIAOMI_NEW_CAMERA_BLOBS=y" ]; then
+    CAMERA="$(grep 'BLOBS' $BUILD/arch/arm64/configs/"${CONFIG}")"
+    if [ "${CAMERA}" == "CONFIG_XIAOMI_NEW_CAMERA_BLOBS=y" ]; then
             CAM_TYPE="newcam"
-        elif [ ${CAMERA} == "CONFIG_XIAOMI_NEW_CAMERA_BLOBS=n" ]; then
+        elif [ "${CAMERA}" == "CONFIG_XIAOMI_NEW_CAMERA_BLOBS=n" ]; then
             CAM_TYPE="oldcam"
     fi
 }
 
+
 function tg_push() {
-	ZIP=${ANYKERNEL_DIR}/$(echo rad*.zip)
-	curl -F document=@$ZIP "https://api.telegram.org/bot${token}/sendDocument" \
-			-F chat_id="${chat_id}" \
+	ZIP=$ANYKERNEL_DIR/$(echo rad*.zip)
+	curl -F document=@"$ZIP" "https://api.telegram.org/bot$token/sendDocument" \
+			-F chat_id="$chat_id" \
 			-F "disable_web_page_preview=true" \
 			-F "parse_mode=html"
 }
@@ -134,5 +134,5 @@ function tg_push() {
 CONFIG=whyred_defconfig # Configuration for oldcam
 type
 check_camera
-echo -e ${green}"Building $TYPE for $CAM_TYPE with Clang"${white}
+echo -e "${green}" "Building $TYPE for $CAM_TYPE with Clang" "${white}"
 build_clang # build_clang or build_gcc
